# -*- coding: utf-8 -*-
"""Untitled149.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLgAiLyyBFmnstPWPMGsFFV45WqLP0FP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('/content/india_job_market_dataset.csv')

df.info()

df['Posted Date'] = pd.to_datetime(df['Posted Date'])
df['Application Deadline'] = pd.to_datetime(df['Application Deadline'])

# ensure salary is standardised for analysis
salary_mapping = { '5-8LPA':6-5,'12-10LPA':16,'20+LPA':25}
df['salary in(LPA)']=df['Salary Range'].map(salary_mapping)

# job demand by location
job_location_counts = df['Job Location'].value_counts()

# job demand by company size
company_size_counts = df['Company Size'].value_counts()

# job demand by job type
job_type_counts = df['Job Type'].value_counts()

# 1. job demand by location
plt.figure(figsize=(10, 6))
job_location_counts.plot(kind='bar')
plt.title('Job Demand by Location')
plt.xlabel('Location')
plt.ylabel('Number of Jobs')
plt.xticks(rotation=45)
plt.show()

#2.job demand by company size
plt.figure(figsize=(10,6))
company_size_counts.plot(kind='bar')
plt.title('Job Demand by Company Size')
plt.xlabel('Company Size')
plt.ylabel('Number of Jobs')
plt.xticks(rotation=45)
plt.show

# 3. Job demand by job type
plt.figure(figsize=(8, 5))
job_type_counts.plot(kind='pie', autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Job Demand by Job Type')
plt.ylabel('')
plt.show()

# 4. Remote, hybrid, and onsite job trends
plt.figure(figsize=(8, 5))
df['Remote/Onsite'].value_counts().plot(kind='bar', color='purple')
plt.title('Job Distribution by Work Type')
plt.ylabel('Number of Jobs')
plt.xlabel('Work Type')
plt.show()